### ISSUE TITLE
Create admin input box for entering tracking ID

### ISSUE THREAD

**Issue by maektwain** [InfluenceIO/wordpress-plugin#1]
Once customer receives pixel code from the dashboard , he can install the plugin from Wordpress index.

He should see a configuration single input form for putting tracking ID.

Functions

Should store trackingID and update trackingID

After actions.

Once tracking ID is stored website should include a pre-defined script inside head tag with trackingID provided.

**Comment by maektwain** [comment]
@ShankyRana Please add the dummy script for the website here.

**Comment by Devilla** [comment]
<script>
new Influence({
trackingId: 'INF-XXXXXXXX'
});
</script>
